#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Frame;
                ref class ContentDialog;
                ref class SplitView;
                ref class ListBox;
                ref class ListBoxItem;
                ref class Button;
                ref class TextBlock;
                ref class AppBarButton;
            }
        }
    }
}

namespace _3dModelsBuilder
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Controls::Frame^ myFrame;
        private: ::Windows::UI::Xaml::Controls::ContentDialog^ CloseFileDialog;
        private: ::Windows::UI::Xaml::Controls::ContentDialog^ SaveFileDialog;
        private: ::Windows::UI::Xaml::Controls::SplitView^ mySplitView;
        private: ::Windows::UI::Xaml::Controls::ListBox^ menu;
        private: ::Windows::UI::Xaml::Controls::ListBoxItem^ home;
        private: ::Windows::UI::Xaml::Controls::ListBoxItem^ editor;
        private: ::Windows::UI::Xaml::Controls::ListBoxItem^ settings;
        private: ::Windows::UI::Xaml::Controls::Button^ HamburgerButton;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TitleTextBlock;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ newButton;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ fileButton;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ saveButton;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ saveAsButton;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ closeButton;
    };
}

