//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "DirectXPage.xaml.h"

void ::_3dModelsBuilder::DirectXPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///DirectXPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::_3dModelsBuilder::DirectXPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 1:
        {
            this->swapChainPanel = safe_cast<::Windows::UI::Xaml::Controls::SwapChainPanel^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::SwapChainPanel^>(this->swapChainPanel))->RightTapped += ref new ::Windows::UI::Xaml::Input::RightTappedEventHandler(this, (void (::_3dModelsBuilder::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::RightTappedRoutedEventArgs^))&DirectXPage::swapChainPanel_RightTapped);
        }
        break;
    case 2:
        {
            this->FileName = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 3:
        {
            this->FileTree = safe_cast<::Windows::UI::Xaml::Controls::ListView^>(__target);
        }
        break;
    case 4:
        {
            this->AddModelButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->AddModelButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::_3dModelsBuilder::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::AddModelButton_Click);
        }
        break;
    case 5:
        {
            this->AddModelOptions = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
        }
        break;
    case 6:
        {
            this->Options = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
        }
        break;
    case 7:
        {
            this->BlueSlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
        }
        break;
    case 8:
        {
            this->BlueText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 9:
        {
            this->GreenSlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
        }
        break;
    case 10:
        {
            this->GreenText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 11:
        {
            this->RedSlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
        }
        break;
    case 12:
        {
            this->RedText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 13:
        {
            this->ScaleSlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
        }
        break;
    case 14:
        {
            this->ScaleText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 15:
        {
            this->ZRotateSlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
        }
        break;
    case 16:
        {
            this->ZRotateText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 17:
        {
            this->YRotateSlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
        }
        break;
    case 18:
        {
            this->YRotateText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 19:
        {
            this->XRotateSlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
        }
        break;
    case 20:
        {
            this->XRotateText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 21:
        {
            this->ZMoveSlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
        }
        break;
    case 22:
        {
            this->ZMoveText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 23:
        {
            this->YMoveSlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
        }
        break;
    case 24:
        {
            this->YMoveText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 25:
        {
            this->XMoveSlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->XMoveSlider))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::_3dModelsBuilder::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&DirectXPage::XMoveSlider_ValueChanged);
        }
        break;
    case 26:
        {
            this->XMoveText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 27:
        {
            this->ModelTypeSwitch = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
        }
        break;
    case 28:
        {
            this->OkButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->OkButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::_3dModelsBuilder::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::OkButton_Click);
        }
        break;
    case 29:
        {
            this->CancelButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->CancelButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::_3dModelsBuilder::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::CancelButton_Click);
        }
        break;
    case 30:
        {
            ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ element30 = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(element30))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::_3dModelsBuilder::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::MenuFlyoutItem_Click);
        }
        break;
    case 31:
        {
            ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ element31 = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(element31))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::_3dModelsBuilder::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::MenuFlyoutItem_Click_1);
        }
        break;
    case 32:
        {
            ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ element32 = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(element32))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::_3dModelsBuilder::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::MenuFlyoutItem_Click_2);
        }
        break;
    case 33:
        {
            this->bottomAppBar = safe_cast<::Windows::UI::Xaml::Controls::AppBar^>(__target);
        }
        break;
    case 34:
        {
            ::Windows::UI::Xaml::Controls::AppBarButton^ element34 = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(element34))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::_3dModelsBuilder::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::AppBarButton_Click);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::_3dModelsBuilder::DirectXPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


